sonar.projectKey=telefonicaid_fiware-orion_ec678f1d-8601-4f38-84b9-07bf54e692d0
sonar.projectName=fiware-orion
sonar.host.url=https://sonarqube-colab.iotplatform.telefonica.com
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=test

sonar.exclusions=\
  **/build/**,\
  **/BUILD_*/**,\
  **/coverage/**,\
  test/**
