FROM ubuntu:20.04

ENV ROOT_FOLDER='/opt'
ENV PAHO_VERSION='v1.3.1'

# Update apt
RUN apt-get -y update

RUN mkdir /tmp/build

COPY ./docker/build/ /tmp/build/

RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN /tmp/build/install-build-dependencies.sh
RUN /tmp/build/install-postgres-client.sh
RUN /tmp/build/install-mongoc-driver.sh
RUN /tmp/build/install-rapid-json.sh
RUN /tmp/build/install-lib-microhttp.sh
RUN /tmp/build/install-k-libs.sh
RUN /tmp/build/install-paho-client.sh
RUN /tmp/build/install-boost-ops-dependencies.sh
RUN /tmp/build/install-test-dependencies.sh
