FROM fiware/orion-ld-base AS build-stage

ARG PATH_TO_SRC='opt/orion/'

RUN cp -a /usr/local/lib/. /usr/lib/x86_64-linux-gnu/
RUN rm -r /usr/local/lib/

COPY . ${PATH_TO_SRC}

WORKDIR ${PATH_TO_SRC}

RUN make release install

RUN strip /usr/bin/orionld

FROM registry.access.redhat.com/ubi8/ubi:8.4

LABEL authors="Ken Zangelin - ken.zangelin@fiware.org, Stefan Wiedemann - stefan.wiedemann@fiware.org" \
      description="Orion-LD is a Context Broker which supports both the NGSI-LD and the NGSI-v2 APIs." \
      maintainer="ken.zangelin@fiware.org,stefan.wiedemann@fiware.org" \
      vendor="FIWARE Foundation e.V." \
      documentation="https://github.com/FIWARE/context.Orion-LD/tree/develop/doc" \
      name="FIWARE Orion-LD" \
      summary="Contains Orion-LD context broker."

ENV LD_LIBRARY_PATH=/opt/paho.mqtt.c/build/output:/usr/local/lib64
RUN mkdir -p /var/{log,run}/orionld

RUN mkdir /licenses
COPY ./LICENSE /licenses/LICENSE

COPY --from=build-stage /etc/ssl/ /etc/ssl/
COPY --from=build-stage /opt/orion/ldcontexts/ /opt/orion/ldcontexts/
COPY --from=build-stage /lib/x86_64-linux-gnu/ /lib/x86_64-linux-gnu/
COPY --from=build-stage /usr/lib /usr/lib
COPY --from=build-stage /usr/bin/ /usr/bin/
COPY --from=build-stage /usr/lib64/ /usr/lib64/
COPY --from=build-stage /usr/local/ /usr/local/
COPY --from=build-stage /opt/paho.mqtt.c/build/output /opt/paho.mqtt.c/build/output

ENTRYPOINT ["orionld", "-fg", "-multiservice", "-ngsiv1Autocast"]

EXPOSE 1026
