FROM fiware/orion-ld-base AS build-stage

ARG PATH_TO_SRC='opt/orion/'

RUN cp -a /usr/local/lib/. /usr/lib/x86_64-linux-gnu/
RUN rm -r /usr/local/lib/

COPY . ${PATH_TO_SRC}

WORKDIR ${PATH_TO_SRC}

RUN  make debug install

RUN strip /usr/bin/orionld

FROM ubuntu:20.04

RUN mkdir -p /var/{log,run}/orionld

COPY --from=build-stage /etc/ssl/ /etc/ssl/
COPY --from=build-stage /opt/orion/ldcontexts/ /opt/orion/ldcontexts/
COPY --from=build-stage /lib/x86_64-linux-gnu/ /lib/x86_64-linux-gnu/
COPY --from=build-stage /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/
COPY --from=build-stage /usr/bin/ /usr/bin/

ADD ./docker/debug/gdbinit gdbinit

RUN apt-get update
RUN apt-get -y install gdb

ENTRYPOINT ["gdb", "-x", "gdbinit", "--args", "orionld", "-fg", "-multiservice", "-ngsiv1Autocast"]

EXPOSE 1026
