FROM fiware/orion-ld-base

ARG PATH_TO_SRC='/opt/orion/'

RUN  yum install -y lcov

RUN  yum install -y gnupg
RUN  wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
RUN  echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
RUN  yum install -y mongodb-org

RUN  yum install -y python2.7
RUN  ln --force -s /usr/bin/python2.7 /usr/bin/python
RUN  yum install -y python-openssl

RUN  wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
RUN  python2.7 get-pip.py
RUN  pip2.7 install Flask
RUN  pip2.7 install paho-mqtt

RUN  yum install -y netcat
RUN  yum install -y bc

COPY . ${PATH_TO_SRC}
WORKDIR ${PATH_TO_SRC}

ENTRYPOINT ["docker/build.sh"]
