ARG BASE_VERSION=latest
FROM fiware/orion-ld:${BASE_VERSION}

ADD ./docker/debug/gdbinit gdbinit

RUN yum -y --nogpgcheck install gdb

ENTRYPOINT ["gdb", "-x", "gdbinit", "--args", "orionld", "-fg", "-multiservice", "-ngsiv1Autocast"]

EXPOSE 1026
