FROM debian:stretch-slim

LABEL maintainer="FIWARE Orion Context Broker Team. Telefónica I+D"

ARG STAGE=release
ARG REV=master

ENV ORION_USER=orion

WORKDIR /opt

COPY . /usr/local/bin/

RUN build.sh -s ${STAGE} -r ${REV} -c -o debian

ENTRYPOINT ["/usr/bin/contextBroker","-fg", "-multiservice", "-ngsiv1Autocast" ]

EXPOSE 1026
