FROM centos:7

ARG TOKEN
ARG STAGE=release
ARG PLATFORM=centos
ARG REV=develop

ENV BROKER='orionld'

WORKDIR /opt

COPY . /usr/local/bin/

RUN build.sh -T ${TOKEN} -p ${PLATFORM} -s ${STAGE} -c -B ${REV}

ENTRYPOINT ["orionld", "-fg", "-multiservice", "-ngsiv1Autocast"]

EXPOSE 1026
