FROM fiware/orion-ld-base

ARG PATH_TO_SRC='/opt/orion/'

RUN  apt-get install -y lcov

RUN  apt-get install -y gnupg
RUN  wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
RUN  echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
RUN  apt-get update
RUN  apt-get install -y mongodb-org

RUN  apt-get install -y python2
RUN  ln -s /usr/bin/python2 /usr/bin/python
RUN  apt-get install -y python-openssl
RUN  pip2.7 install Flask

RUN  apt-get install -y netcat
RUN  apt-get install -y bc

COPY . ${PATH_TO_SRC}
WORKDIR ${PATH_TO_SRC}

ENTRYPOINT ["docker/build.sh"]
