FROM centos:7

ARG TOKEN
ARG STAGE=release
ARG OS=centos
ARG REV=develop

ENV BROKER='orionld'

WORKDIR /opt

COPY . /usr/local/bin/

RUN build.sh -T ${TOKEN} -o ${OS} -s ${STAGE} -r ${REV} -c

ENTRYPOINT ["orionld", "-fg", "-multiservice", "-ngsiv1Autocast"]

EXPOSE 1026
