FROM fiware/orion-ld-base

ARG PATH_TO_SRC='/opt/orion/'
ENV LD_LIBRARY_PATH=/opt/paho.mqtt.c/build/output:/usr/local/lib64

RUN  wget http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
RUN tar -xf lcov-1.14.tar.gz
WORKDIR lcov-1.14
RUN make install
WORKDIR ${PATH_TO_SRC}

RUN  yum install -y gnupg

RUN yum install -y https://repo.mongodb.org/yum/redhat/8Server/mongodb-org/4.4/x86_64/RPMS/mongodb-database-tools-100.4.1.x86_64.rpm
RUN yum install -y https://repo.mongodb.org/yum/redhat/8Server/mongodb-org/4.4/x86_64/RPMS/mongodb-org-database-tools-extra-4.4.9-1.el8.x86_64.rpm
RUN yum install -y https://repo.mongodb.org/yum/redhat/8Server/mongodb-org/4.4/x86_64/RPMS/mongodb-org-tools-4.4.9-1.el8.x86_64.rpm
RUN yum install -y https://repo.mongodb.org/yum/redhat/8Server/mongodb-org/4.4/x86_64/RPMS/mongodb-org-shell-4.4.9-1.el8.x86_64.rpm
RUN yum install -y https://repo.mongodb.org/yum/redhat/8Server/mongodb-org/4.4/x86_64/RPMS/mongodb-org-server-4.4.9-1.el8.x86_64.rpm
RUN yum install -y https://repo.mongodb.org/yum/redhat/8Server/mongodb-org/4.4/x86_64/RPMS/mongodb-org-mongos-4.4.9-1.el8.x86_64.rpm
RUN yum install -y https://repo.mongodb.org/yum/redhat/8Server/mongodb-org/4.4/x86_64/RPMS/mongodb-org-4.4.9-1.el8.x86_64.rpm
RUN yum install -y mongodb-org

RUN yum install -y python2
RUN ln --force -s /usr/bin/python2.7 /usr/bin/python
RUN ln -s /usr/lib64/libgnutls.so.30 /usr/lib64/libgnutls.so

RUN yum install -y openssl-devel libffi-devel

RUN wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
RUN python2.7 get-pip.py
RUN pip2.7 install Flask
RUN pip2.7 install paho-mqtt
RUN pip2.7 install pyopenssl

RUN yum install --nogpgcheck -y gmock-devel
RUN yum install -y procps

RUN wget https://github.com/google/googletest/archive/release-1.5.0.tar.gz
RUN tar xf release-1.5.0.tar.gz
WORKDIR googletest-release-1.5.0
RUN cmake -DBUILD_SHARED_LIBS=ON .
RUN make
RUN cp -a googletest/include/gtest /usr/include
RUN cp -a googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so /usr/lib/
RUN ldconfig -v | grep gtest
WORKDIR ${PATH_TO_SRC}

RUN yum install -y netcat
RUN yum install -y bc
RUN yum -y install hostname

COPY . ${PATH_TO_SRC}
WORKDIR ${PATH_TO_SRC}


ENTRYPOINT ["docker/build.sh"]
