FORMAT: 1A
HOST: http://orion.lab.fiware.org
TITLE: FIWARE-NGSI v2 Specification
DATE: 30 September 2015
VERSION: 2.0-latest
PREVIOUS_VERSION: <placeholder>
APIARY_PROJECT: fiware-ngsi-v2
SPEC_URL: https://telefonicaid.github.io/fiware-orion/api/v2/
GITHUB_SOURCE: http://github.com/telefonicaid/fiware-orion.git

# FIWARE-NGSI v2 Specification

This specification defines the FIWARE-NGSI version 2 API. FIWARE-NGSI v2 is intended to manage all the whole lifecycle of
context information including updates, queries, registrations and subscriptions.

# Preface

## Editors

José Manuel Cantera Fonseca (Telefónica I+D), Fermín Galán Márquez (Telefónica I+D), Tobias Jacobs (NEC).
  
## Acknowledgements

The editors would like to express their gratitude to the following people who actively contributed to this specification:
Juan José Hierro (Telefónica I+D), Marcos Reyes (Telefónica I+D), Ken Zangelin (Telefónica I+D), Iván Arias López (Telefónica I+D),
Carlos Romero Brox (Telefónica I+D), Antonio José López Navarro (Telefónica I+D),  Marc Capdevielle (Orange), Gilles Privat (Orange), 
Sergio García Gómez (Telefónica I+D), Martin Bauer (NEC).
  
## Status

This is a work in progress and is changing on a daily basis.
Please send your comments to fiware-ngsi@lists.fiware.org. You can
trace the discussions checking the archives of the mailing list:
https://lists.fiware.org/private/fiware-ngsi/ (list subscription
required).

In addition, note that a list of currently open discussions is available at

* https://github.com/telefonicaid/fiware-orion/issues/1022
* https://github.com/telefonicaid/fiware-orion/issues/1034
* https://github.com/telefonicaid/fiware-orion/issues/1035

## Copyright

This specification is licensed under the
[FIWARE Open Specification License (implicit patent license)]
(http://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/FI-WARE_Open_Specification_Legal_Notice_(implicit_patents_license)).

## Conformance

This specification describes the "full" compliance level.

However, next iterations of this specification could define optionality
in some parts and the compliance level (or roles/profiles)
corresponding to them.

## Conventions

NGSI version 2 use camel case (camelCase) syntax for naming properties and related artifacts used by the API. When 
referring to URIs, as part of HATEOAS patterns, and to mark them appropriately the suffix `_url` is added.

# Specification

## Introduction

The FIWARE NGSI (Next Generation Service Interface) API defines 

* a **data model** for context information, based on a simple information model using the notion of *context entities*
* a **context data interface** for exchanging information by means of query, subscription, and update operations
* a **context availability interface** for exchanging information on how to obtain context information
(whether to separate the two interfaces is currently under discussion).
* a set of typical **roles** played by NGSI-compliant components

## Terminology

### Context data modelling and exchange

The main elements in the NGSI data model are context entities, attributes and metadata, as shown
in the figure below.

![NGSI data model](https://raw.githubusercontent.com/telefonicaid/fiware-orion/develop/doc/apiary/v2/Ngsi-data-model.png)

#### Context Entities

Context entities, or simply called entities, are the center of gravity
in the FIWARE NGSI information model. An entity represents a
thing, i.e. any physical or logical object (e.g. a sensor, a person, a room, an
issue in a ticketing system, etc.). Each entity has an **entity id**.

Furthermore, the type system of FIWARE NGSI enables entities to have 
an **entity type**. Entity types are semantic types; they are intended
to describe the type of things represented by the entity.
For example, a context entity with id *sensor-365* could have the
type *temperatureSensor*.

Each entity is uniquely identified by the combination of its id
and type.

#### Context Elements

*(Note: the distinction between context entities and context elements 
is still under discussion; therefore the notion of context elements
currently only appears in this section.)*

A context element is a data object (e.g. JSON object; see the section
on JSON representation below) which contains information about a
specific context entity. Consequently, a context element has a
mandatory property `id` in order to identify the context entity it
refers to. It furthermore can contain an optional property `type`
to describe the type of the entity. Further properties can be used
to represent more information about the entity (see the **context
attributes** section below).

It is important to understand that the relationship of entity and context element is one-to-many. This means that 
* each context element refers to exactly one entity
* there can be several context elements  referring to the same entity. The context elements can for example contain
different pieces of information about the entity

#### Context Attributes 

Context attributes are properties of context entities.
For example, the current speed of a car could be modeled as
attribute *current_speed* of entity *car-104*.

In the NGSI data model, attributes have an *attribute name*,
an *attribute type*, an *attribute value* and *metadata*. 
 * The attribute name describes which kind of property of the entity the attribute value represents, for example *current_speed*.
 * The attribute type represents the NGSI value type of the attribute value.
 Note that FIWARE NGSI has its own type system for attribute values, so NGSI value types are not the same as JSON types.
 * The attribute value finally contains
  * the actual data
  * optional **metadata** describing properties of the attribute value like e.g. accuracy, provider, or a timestamp
  
#### Context Metadata

Context metadata is used in FIWARE NGSI at several places, one of
them being an optional part of the attribute value as described
above. Similarly to attributes, each piece of metadata has 
 * **a metadata name**, describing the role of the metadata at the
 place where it occurs; for example, the metadata name *accuracy* 
 indicates that the metadata value describes how accurate a given 
 attribute value is
 * a **metadata type**, describing the NGSI value type of the metadata value
 * a **metadata value** containing the actual metadata

Note that in NGSI it is not foreseen that metadata values can
themselves have metadata.

#### Restrictions and Operation Scopes

(placeholder to describe restrictions and operation scopes)

#### Context Queries

(placeholder for describing what a context query is, and some hints on how this
is typically done in the REST interface)

#### Context Subscriptions

(placeholder for describing the concept of context subscriptions)

#### Context Updates

(placeholder for describing updates)

### Exchanging Context Availability Information

(placeholder on some introduction of what context availability information is)

#### Context Registrations

(placeholder for describing what a context registration is and what it is used for)

#### Context Discovery

(placehoder for describing what discovery does)

#### Context Availability Subscription

(placeholder for describing context availability subscriptions)

#### Registering Context Availability Information

(placeholder for describing the operation of registering context)

### Roles of FIWARE NGSI components

(placeholder to describe roles like context provider, context producer,
context broker, context registry, context consumer)

## JSON Entity Representation

An entity is represented by a JSON object with the following syntax:

* The entity id is specified by the object's `id` property, which value is a string containing the entity id.

* The entity type is specified by the object's `type` property, which value is a string containing the entity's type name.

* Entity attributes are specified by additional properties, which name is the `name` of the attribute and which representation
  is described in the "JSON Attribute Representation" section below. Obviously, `id` and `type` are not allowed as attribute names.

An example of this syntax in shown below:

```
{
  "id": "entityID",
  "type": "entityType",
  "attr_1": <val_1>,
  "attr_2": <val_2>,
  ...
  "attr_N": <val_N>
}
```

The normalized representation of entities always include `id`, `type` and the properties which represent attributes. However, simplified
or partial representations (see below at "Partial Representations" section), may leave out some of them. The specification of each operation
includes details about what  representation is expected as input or what representation will be provided (rendered) as output.

## JSON Attribute Representation

An attribute is represented by a JSON object with the following syntax:

* The attribute value is specified by the `value` property, which value may be any JSON datatype.

* The attribute NGSI type is specified by the `type` property, which value is a string containing the NGSI type.

* The attribute metadata is specified by the `metadata` property. Its value is another JSON object which will contain a
  property per metadata element defined (the name of the property is the `name` of the metadata element). Each metadata element,
  in turn, is represented by a JSON object containing the following properties:

  * `value`: Its value will contain the metadata value, which may correspond to any JSON datatype.

  * `type`: Its value will contain a string representation of the metadata NGSI type.

An example of this syntax in shown below:

```
{
  "value": <...>,
  "type": <...>,
  "metadata": <...>
}
```

## Simplified Entity Representation

There are two representation modes, which must be supported by implementations, and which allow to generate simplified representations of entities.

* *keyValues* mode. This mode represents each entity attribute only by its value, leaving out the information about type and metadata.
  Thus, when this mode is on, only the attribute value is represented and will correspond to the value of the property which represents the attribute.
  See example below.

```
{
   "id": "R12345",
   "type": "Room",
   "temperature": 22
}
```

* *values mode*. This mode represents the entity only by a collection of attribute values conveyed by an Array. Id and type information are left out.
  See example below. The order of the attributes in the Array is specified by the `attrs` URI param (e.g. `attrs=branch,colour,engine`) or arbitrary
  order in the case `attrs` is not used.

```
[ 'Ford', 'black', 78.3 ]
```

* *unique mode*. This mode is just like *values mode*, with the only difference that values are not repeated.

## Partial Representations

Some operations imply that only a partial representation of an entity will be provided, which are summarized below:

* `id` and `type` are not allowed in update operations, as they are inmutable properties.

* In the requests in which entity `type` is allowed, it may be omitted. When omitted in entity creation operations,
  the default string value `none` is used for the type.

* In some cases, not all the attributes of the entity are shown, e.g. a query which selects a subset of entity attributes.

* Attribute/metadata `value` may be omitted in requests, meaning that the attribute/metadata has `null` value. It is always present in responses.

* Attribute/metadata `type` may be ommitted in requests. When omitted in attribute/metadata creation or update operations, the default
  string value `none` is used for the type.

* Attribute `metadata` may be ommitted in requests, meaning that there are not metadata elements associated to the attribute. In responses, this property is set to
  `{}` if the attribute doesn't have metadata.


## Special Attribute Types

Generally speaking, user-defined attribute types are informative, they are processed by the NGSIv2 server in
an opaque way. Nonetheless, the types described below are used to convey an special meaning

* `date`:  identifies dates, in ISO8601 format. These attributes can be used with the
  greater than, less than, greater or equal, lesser or equal and range query operators. For instance
  (only the referred entity attribute is shown) :

```
{
  "timestamp": {
    "value": "2017-06-17T07:21:24.238Z",
    "type: "date"
  }
}
```

## Virtual Attributes

There are entity properties that are not directly modificable by NGSIv2 clients, but that can be rendered
by NGSIv2 servers to provide extra information. From a representation point of view, they are like
regular attributes, with name, value and type.

Virtual attributes are not rendered by default. In oder to render an specific attribute, add its name
to the `options` URL parameter.

The list of virtual attributes is the following:

* `dateCreated` (type: `date`): entity creation date as ISO 8601 string.
* `dateModified` (type: `date`): entity modification date as ISO 8601 string.

As regular attributes, they can be  used in `attrs`, `q` filters and `orderBy`. However, they cannot be used
in resource URLs.


## Field syntax restrictions

Fields used as identifiers in the NGSIv2 API follow special rules regarding allowed syntax. These rules applies to:

* Entity id
* Entity type
* Attribute name
* Attribute type
* Metadata name
* Metadata type

The rules are:

* Allowed characters are the ones in the plain ASCII set except the following ones: control characters, whitespace, `&`, `?`, `/` and `#`.
* Maximum field length is 256 characters.
* Minimum field length is 1 character.

In addition to the above rules, given NGSIv2 server implementations could add additional syntactical restrictions in those
or other fields, e.g. to avoid some cross script injection attacks.

In the case a client attemps to use a field not valid from a syntax point of view, it shall get a "Bad Request" error
explaining the cause.

## Atrribute names restrictions

The following strings must not be used as attribute names:

* `id`, as it would conflict to the field used to represent entity id.

* `type`, as it would conflict to the field used to represent entity type.

* `geo:distance`, as it would conflict with the string used in `orderBy` for proximity to center point.

* Virtual attribute names (see specific section on "Virtual Attributes")

## Ordering Results

Operations that retrieve lists of entities allow the `orderBy` URI parameter to specify which attributes or properties will
be used as criteria to order results. Its value can be:

* The keyword `geo:distance` to order results by distance to a reference geometry when a "near" (`georel=near`) spatial
  relationship is used. 

* A comma-separated list of attributes (including virtual attributes), e.g. `temperature,!humidity`. Results are ordered
  by the first attribute. On ties, the results are ordered by the second attribute and so on. A "!" before the attribute
  name means that the order is reversed.

## Error Responses

In the case of being present, the error payload is a JSON object including the following fields:

+ `error` (required, string): a textual description of the error.
+ `description` (optional, string): additional information about the error.
+ `affectedItems` (optional, array[string]): a list of elements affected by the error. Depending on the operation, it may
  refer to entities, registrations or subscriptions.

All NGSIv2 server implementations must use the following HTTP response codes and `error` texts. However, the particular text used for
`description` field is an implementation specific aspect.

Error list (HTTP response code in parenthesis):

* ParseError            (`400`). The incoming JSON payload cannot be parsed.
* BadRequest            (`400`). The incoming request is invalid in this context.
* NotFound              (`404`). The resource (entity, subscription, etc.) referred in the request has not been found.
* TooManyResults        (`409`). There are several results that match with the resource identification used by the request.
* ContentLengthRequired (`411`). Zero/No Content-Length in PUT/POST/PATCH request.
* RequestEntityTooLarge (`413`). Payload is too large.
* UnsupportedMediaType  (`415`). Request content type is not supported.
* InvalidModification   (`422`). Some piece of information is missing in payload.
* NotSupportedQuery     (`422`). The implementation does not support the query issued.
* NoResourcesAvailable  (`413`). There are no server resources to fulfill the client request. 

New error codes could be defined in new iterations of this specification.

## Geospatial properties of entities

The geospatial properties of a context entity can be represented by means of regular context attributes.
The provision of geospatial properties enables the resolution of geographical queries.

Two different syntaxes must be supported by compliant implementations: 

* *Simple Location Format*. It is meant as a very lightweight format that developers and users can quickly
and easily add to their existing entities with little effort.

* *GeoJSON*.  [GeoJSON](https://tools.ietf.org/html/draft-butler-geojson-06)
is a geospatial data interchange format based on the JavaScript Object Notation (JSON). GeoJSON provides greater flexibility
allowing the representation of point altitudes or even more complex geospatial shapes, for instance
[multi geometries](http://www.macwright.org/2015/03/23/geojson-second-bite.html#multi-geometries).

Client applications are responsible for defining which entity attributes convey geospatial properties (by providing
an appropriate NGSI attribute type). Typically it will be an entity attribute named `location`,
but nothing prevents use cases where an entity contains more than one geospatial attribute. For instance,
locations specified at different granularity levels or provided by different location methods with different accuracy. 
Nonetheless, it is noteworthy the fact that spatial properties
need special indexes which can be under resource constraints imposed by backend databases.
Thus, implementations may raise errors when spatial index limits are exceeded.
The recommended HTTP status code for those situations is ``413``, *Request entity too large*, and the reported error
on the response payload must be ``NoResourcesAvailable``.

*Note: At the time of writing it is still under discussion if supporting both syntaxes is really needed* 

### Simple Location Format

Simple Location Format supports basic geometries ( *point* , *line* , *box* , *polygon* ) and covers the typical
use cases when encoding geographical locations. It has been inspired by [GeoRSS Simple](http://www.georss.org/simple.html).

It is noteworthy that the Simple Location Format is not intended to represent complex positions on Earth surface.
For instance, those applications which require to capture altitude coordinates will have to use GeoJSON as
representation format for the geospatial properties of their entities. 

A context attribute  which represents a location encoded using the Simple Location Format
must conform to the following syntax:

* The attribute type must be one of the following values: (`geo:point`, `geo:line`, `geo:box` or `geo:polygon`).
* The attribute value must be a list of coordinates. By default coordinates will be defined
using the [WGS84 Lat Long](https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84),
[EPSG::4326](http://www.opengis.net/def/crs/EPSG/0/4326) coordinate reference system (CRS),
with latitude and longitude units of decimal degrees. Such coordinate list will allow to encode the geometry
specified by the `type` attribute and will be encoded according with the specific rules defined below:

  * Type `geo:point`:   the attribute value must contain a string containing a
  valid latitude-longitude pair, separated by a comma. 
  * Type `geo:line`:    the attribute value must contain a string array of
  valid latitude-longitude pairs. There must be at least two pairs.
  * Type `geo:polygon`: the attribute value must contain a string array
  of valid latitude-longitude pairs.
There must be at least four pairs, with the last being identical to the first
(so a polygon has a minimum of three actual points).
Coordinate pairs should be properly ordered so that the line segments
that compose the polygon remain on the ​outer ​edge of the area defined.
For instance, the following path, ```[0,0], [0,2], [2,0], [2, 2]```, is an example of an invalid polygon definition. 
Implementations should raise an error when none of the former conditions are met by input data. 
  * Type `geo:box`:     A bounding box is a rectangular region, often used to define the extents of a map or
a rough area of interest. A box is represented by a two-length string array of latitude-longitude pairs.
The first pair is the lower corner, the second is the upper corner.

Note: Circle geometries are not supported, as the [literature](https://github.com/geojson/geojson-spec/wiki/Proposal---Circles-and-Ellipses-Geoms#discussion-notes)
describes different shortcomings for implementations. 

The examples below illustrate the referred syntax:

```
{
  "location": {
    "value": "41.3763726, 2.186447514",
    "type": "geo:point"
  }
}
```

```
{
  "location": {
    "value": [
              "40.63913831188419, -8.653321266174316",
              "40.63881265804603, -8.653149604797363"
    ],
    "type": "geo:box"
  }
}
```

### GeoJSON

A context attribute which represents a location encoded using GeoJSON must conform to the following syntax:

* The NGSI type of the attribute must be `geo:json`.
* The attribute value must be a valid GeoJSON object. It is noteworthy that longitude comes first in GeoJSON coordinates.

The example below illustrates the usage of GeoJSON.
More GeoJSON examples can be found at [GeoJSON IETF Spec](https://tools.ietf.org/html/draft-butler-geojson-06#page-14).
Additionally, the following [GeoJSON Tutorial](http://www.macwright.org/2015/03/23/geojson-second-bite.html)
can be useful in urderstanding the format. 

```
{
  "location": {
    "value": {
      "type": "Point",
      "coordinates": [2.186447514, 41.3763726]
    },
    "type": "geo:json"
  }
}
```

## Simple Query Language

The Simple Query Language provides a simplified syntax to retrieve entities which match a set of conditions.
A query is composed by a list of statements separated by the ';' character. Each statement express a matching condition.
The query will return all the entities which match all the matching conditions (AND logical operator). 

There are two kind of statements: *unary statements* and *binary statements*.

Binary statements are composed by an attribute name (e.g. "temperature"), operator and value (which format
depends on the operator), e.g.:

```
temperature==50
temperature<=20
```

The list of operators (and the format of the values they use) is as follows:

+ **Equal**: `==`. It accepts the following values:
    + Single element, e.g. `temperature==40`. It matches entities whose attribute value
      that exact value.
    + A list of comma-separated values, e.g. `color==black,red`. It matches entities whose
      attribute value is one of the values (OR clause). Eg. entities which `color` is set to
      `black` will match, while entities which `color` is set to `white` will not match.
    + A range, specified as a minimum and maximum separated by `..`. It matches if
      the value is in the interval between the minimum and the maximum (both included). It can only be used
      with attributes which contain dates (ISO8601 format), numbers or strings. E.g. `temperature==10..20` matchs if the
      temperature is greater or equal than 10 and lower or equal than 20.
+ **Unequal**: `!=`. It accepts the following values:
      + The value is a single element, e.g. `temperature!=40`. It matches entities whose attribute
      value is not that exact value.
      + A list of comma-separated values, e.g. `color!=black,red`. It matches entities whose
      attribute value is not any of the values (AND clause). Eg. entities whose `color` is set
      to `black` will not match, while entities whose `color` is set to `white`will match.
      + A range, specified as a minimum and maximum separated by `..`. It matches
      if the value is not in the interval between the minimum and the maximum (both included). It can only
      be used with attributes which contain dates (ISO8601 format), numbers or strings. E.g. `temperature!=10..20` matches if
      the temperature is lower than 10 or greater than 20 (it will not match if the tempeature is 10 or the
      temperature is 20).
+ **Greater than**: `>`. The value is a single element, e.g. `temperature>40`. It
  matches entities which attribute value is strictly greater than that value. It only makes sense when
  used with attributes which contain dates, numbers or strings (using with attributes of other type might lead to
  unexpected results).
+ **Less than**: `<`. The value is a single element, e.g. `temperature<40`. It
  matches entities which attribute value is strictly less than that value. It only makes sense when
  used with attributes which contain dates, numbers or strings (using with attributes of other type might lead to
  unexpected results).
+ **Greater or equal than**: `>=`. The value is a single element, e.g. `temperature>=40`.
  It matches entities which attribute value is greater than or equal to that value. It only makes sense when
  used with attributes which contain dates, numbers or strings (using with attributes of other type might lead to
  unexpected results).
+ **Less or equal than**: `<=`. The value is a single element, e.g. `temperature<=40`. It
  matches entities which attribute value is less than or equal to that value. It only makes sense when
  used with attributes which contain dates, numbers or strings (using with attributes of other type might lead to
  unexpected results).
+ **Match pattern**: `~=`. The value matches a given pattern, expressed as a regular expression, e.g.
  `color=ow` matches `brown` or `yellow`. It only makes sense when used with attributes which contain strings.

The symbol `:` can be used as synonym of `==`.

In the case of equal or unequal, if the value to match include a `,`, you can use simple quote
(`'`), e.g: `color=='light,green','deep,blue'`.

Unary negatory statements use the unary operator `!`, while affirmative unary statements use no operator at all.
The unary statements are used to check for attribute existence. E.g. `temperature` matches entities that have
an attribute called 'temperature' (no matter its value), while `!temperature` matches entities that do not have
a temperature attribute.
  
 
## Geographical Queries

Geographical queries are specified by means of the following parameters:

``georel`` is intended to specify a spatial relationship (a predicate)
between matching entities and a reference shape (`geometry`).
It is composed of a token list separated by ';'.
The first token is the relationship name, the rest of tokens (if any) are modifiers which
provide more information about such a relationship. The following values are allowed:

+ `georel=near`. The ``near`` relationship means that matching entities must be located at certain threshold
distance to the reference geometry. It supports the following modifiers:
  + `maxDistance`.  Express, in meters, the maximum distance at which matching entities must be located.
  + `minDistance`.  Express, in meters, the minimum distance at which matching entities must be located.
+ `georel=coveredBy`. Denotes that matching entities are those which exist entirely within the reference geometry.
When resolving this query the border of a shape must be considered to be part of the shape. 
+ `georel=intersects`. Denotes that matching entities will be those intersecting with the reference geometry.
+ `georel=equals`. The geometry associated to the position of matching entities
and the reference geometry must be exactly the same.
+ `georel=disjoint`. Denotes that matching entities will be those NOT intersecting with the reference geometry. 

`geometry` allows to define the reference shape to be used when resolving the query.
 The following geometries (see Simple Location Format) must be supported:

+ `geometry=point`, defines a point on the Earth surface.
+ `geometry=line`, defines a polygonal line.
+ `geometry=polygon`, defines a polygon.
+ `geometry=box`, defines a bounding box.

**coords** must be a string containing a semicolon separated list of pairs of geographical coordinates
in accordance with the geometry specified and the rules mandated by the Simple Location Format:

* `geometry=point`.   `coords` will contain a pair of WGS-84 geo-coordinates.
* `geometry=line`.    `coords` will contain a list of pairs of WGS-84 geo-coordinates.
* `geometry=polygon`. `coords` will be composed by at least four pairs of WGS-84 geo-coordinates.
* `geometry=box`.     `coords` will be composed by two pairs of WGS-84 geo-coordinates.

Examples:

`georel=near;maxDistance:1000&geometry=point&coords=-40.4,-3.5`.
Matching entities will be located, at a maximum, 1000 meters far away from the reference point.

`georel=near;minDistance:5000&geometry=point&coords=-40.4,-3.5`.
Matching entities will be at least 5000 meters far away from the reference point. 

`georel=coveredBy&geometry=polygon&coords=25.774,-80.190;18.466,-66.118;32.321,-64.757;25.774,-80.190`
Matching entities will be those located within the referred polygon.

### Query Resolution

If an implementation is not able to resolve a geographical query, the HTTP Status code of the response
must be ```422```, *Unprocessable Entity*. The error name present in the error payload must be
``NotSupportedQuery``. 

When resolving geographical queries, through the Simple Query Language,
the API implementation is responsible for determining which entity attribute
contains the geographical location to be used for matching purposes.
To this aim, the following rules must be followed:

* If an entity has no attribute which corresponds to a location (encoded as GeoJSON or the
Simple Location Format), then such an entity has not declared any geospatial property and will not match any
geographical query.

* If an entity only exposes one attribute corresponding to a location, then such an attribute will be used when
resolving geographical queries.

* If an entity exposes more than one location, then the attribute which contains a metadata property
named ``defaultLocation``, with boolean value ``true``
will be taken as the reference location used for resolving geographical queries.

* If there is more than one attribute exposing location but none of them has been labeled as being the
default location, then the query will be declared as ambigous and an HTTP error response with code ``409``
must be sent.

* If there is more than one attribute exposing location which has been labeled as being the
*default location*, then the query will be declared as ambigous and an HTTP error response with code ``409``
must be sent. 

## Notification Messages

Notifications include two fields:

* `subscriptionId` which represents the concerned subscription that originates the notification
* `data` an array with the notification data itself which includes the entity and all attributes concerned. Each
  element in the array corresponds to a different entity. By default, each entity is represented in
  normalized mode. However by using the `attrsFormat` modifier, a simplified representation can be requested.

If `attrsFormat` is `normalized` (or if `attrsFormat` is omitted) then default entity representation is used:

```
{
   "subscriptionId": "12345",
   "data": [
     {
       "id": "Room1",
       "type": "Room",
       "temperature": {
         "value": 23,
         "type": "none",
         "metadata": {}
       },
       "humidity": {
         "value": 70,
         "type": "percentage",
         "metadata": {}
       }
     },
     {
     "id": "Room2",
     "type": "Room",
     "temperature": {
       "value": 24,
       "type": "none",
       "metadata": {}
     }
   ]
}
```

If `attrsFormat` is `keyValues` then keyValues entity partial representation mode is used:

```
{
   "subscriptionId": "12345",
   "data": [
     {
       "id": "Room1",
       "type": "Room",
       "temperature": 23,
       "humidity": 70
       }
     },
     {
     "id": "Room2",
     "type": "Room",
     "temperature": 24
     }
   ]
}
```


If `attrsFormat` is `values` then values entity partial representation mode is used:

```
{
   "subscriptionId": "12345",
   "data": [ [23, 70], [24] ]
}
```

Notifications must include a `Ngsiv2-AttrsFormat` header with the value of `attrsFormat` of the associated subscription,
so that notification receivers will know the format used without having to process the notification payload.

## Custom Notifications

NGSIv2 clients can customize HTTP notification messages using a simple template mechanism. The
`notification.httpCustom` property of a subscription allows to specify the following fields subject
to be templatized:

* `url`
* `headers` (both header names and values)
* `qs` (both in parameter names and values)
* `payload`

In addition the HTTP method to be used for delivering the notification can be customized as well using the `method` field,
but it cannot be a template.

Macro substitution for templates is based on the syntax `${..}`. In particular:

* `${id}` is replaced by entity id
* `${type}` is replaced by entity type
* Any other `${token}` is replaced by the value of attribute which name is `token` or with
  an empty string if the attribute is not included in the notification. If the value is a number,
  a bool or null then its string representation is used. If the value is a JSON array or object
  then its JSON representation as string is used.

Example:

Let's consider the following `notification.httpCustom` object in a given subscription.

```
"httpCustom": {
  "url": "http://foo.com/entity/${id}",
  "headers": {
    "Content-Type": "text/plain"
  },
  "method": "PUT",
  "qs": {
    "type": "${type}"
  },
  "payload": "The temperature is ${temperature} degrees"
}
```

Now, let's consider that NGSIv2 implementation triggers a notification associated to this subscription.
Notification data is for entity with id "DC_S1-D41" and type "Room", including an attribute named
"temperature" with value 23.4. The resulting notification after applying the template would be:

```
PUT http://foo.com/entity/DC_S1-D41?type=Room
Content-Type: text/plain
Content-Length: 31

The temperature is 23.4 degrees
```

Some considerations to take into account:

* It is the NGSIv2 client's responsability to ensure that after substitution the notification is a correct
  HTTP message (e.g. the Content-Type header is application/xml but the payload doesn't correspond to a
  well-formed XML document). Specifically, if the resulting URL after appliyng the template is malformed,
  then the notification is skipped.
* In case the data to notify contains more than one entity, a separate notification (HTTP message) is sent
  for each of the entities (contrary to default behaviour, which is to send all entities in the same HTTP message).

Note that if a custom payload is used for the notification (the field `payload` is given in the corresponding subscription),
then a value of `custom` is used for the `Ngsiv2-AttrsFormat` header.

## Group API Entry Point

### Retrieve API Resources [GET /v2]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

It is recommended to follow the “url” link values,
[Link](https://tools.ietf.org/html/rfc5988) or Location headers where
applicable to retrieve resources. Instead of constructing your own URLs,
to keep your client decoupled from implementation details.


+ Response 200 (application/json)

    + Attributes (object)
        + entities_url: /v2/entities (required, string) - URL which points to the entities resource
        + types_url: /v2/types (required, string) - URL which points to the types resource
        + subscriptions_url: /v2/subscriptions (required, string) - URL which points to the subscriptions resource
        + registrations_url: /v2/registrations (required, string) - URL which points to the registrations resource

# Group Entities

### List entities [GET /v2/entities{?limit,offset,options,type,id,idPattern,q,georel,geometry,coords,attrs,orderBy}]

Retrieves a list of entities which match different criteria (by id, idPattern, type or those which match
a query or geographical query). A given entity have to match all the criteria to be retrieved
(i.e. criteria are combined in a logical AND way). Note that id and idPattern parameters are incompatible in the same request.
See [Simple Query Language](#simple_query_language) and [Geographical Queries](#geographical_queries). 

The response payload is an Array which contains one object per matching entity. Each entity follows
the JSON entity representation format (described in "JSON Entity Representation" section).

Response code:

* Successful operation uses 200 OK
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + id: Boe_Idearium (optional, string) - A comma separated list of elements.
    Retrieve entities which ID match one of the elements in the list. Incompatible with idPattern.
    
    + type: Room (optional, string) -  comma separated list of elements.
    Retrieve entities which type match one of the elements in the list.

    + idPattern: Bode_.* (optional, string) - A correctly formated regular expression.
    Retrieve entities which ID matches the regular expression. Incompatible with id.
    
    + q: temperature>40 (optional, string) - A query expression, composed of a list of statements separated by `;`,
    i.e. q=statement;statements;statement. See [Simple Query Language specification](#simple_query_language). 
    
    + georel: near (optional, string) - Spatial relationship between matching entities and a reference
    shape. See [Geographical Queries](#geographical_queries).

    + geometry: point (optional, string) - Geografical area to which the query is restricted.
    See [Geographical Queries](#geographical_queries).
    
    + coords: 40.6391,-8.6533 (optional, string) - List of latitude-longitude pairs of coordinates separated by ';'.
    See [Geographical Queries](#geographical_queries).
    
    + limit: 20 (optional, number) - Limits the number of entities to be retrieved
    
    + offset: 20 (optional, number) - Establishes the offset from which entities will be returned
    
    + attrs: seatNumber (optional, string) - Comma-separated list of attribute names which data will be included in the response.
    The attributes are retrieved in the order specified by this parameter. If this parameter is not included, all the attributes
    are retrieved in arbitrary order.

    + orderBy: temperature,!speed (optional, string) - Criteria for ordering results. See "Ordering Results" section for details.
    
    + options (optional, string) - Options dictionary
      + Members
          + count - when used, the total number of entities is returned in the response as a HTTP header named `Fiware-Total-Count`.
          + keyValues - when used, the response payload uses `keyValues` simplified entity representation. See "Simplified Entity Representation"
          section for details.
          + values - when used, the response payload uses `values` simplified entity representation. See "Simplified Entity Representation"
          section for details.
          + unique - when used, the response payload uses `values` simplified entity representation. And, recurring values are left out.
          See "Simplified Entity Representation" section for details.

+ Response 200 (application/json)

        [
         {
            "type": "Room",
            "id": "DC_S1-D41",
            "temperature": {
                "value": 35.6,
                "type": "none",
                "metadata": {}
            }
         },
         {
            "type": "Room",
            "id": "Boe-Idearium",
            "temperature": {
                "value": 22.5,
                "type": "none",
                "metadata": {}
            }
         },
         {
            "type": "Car",
            "id": "P-9873-K",
            "speed": {
                "value": 100,
                "type": "number",
                "metadata": {
                    "accuracy": {
                        "value": 2,
                        "type": "none"
                    },
                    "timestamp": {
                        "value": "2015-06-04T07:20:27.378Z",
                        "type": "date"
                    }
                }
            }
         }
        ]

### Create entity [POST /v2/entities{?options}]

The payload is an object representing the entity to be created. The object follows
the JSON entity representation format (described in a "JSON Entity Representation" section).

Response:

* Successful operation uses 201 Created. Reponse includes a `Location` header with the URL of the
  created entity.
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Request (application/json)

        {
            "type": "Room",
            "id": "Bcn-Welt",
            "temperature": {
                "value": 21.7
            },
            "humidity": {
                "value": 60
            },
            "location": {
                "value": "41.3763726, 2.1864475",
                "type": "geo:point",
                "metadata": {
                    "crs": {
                        "value": "WGS84"
                    }
                }
            }
        }

+ Parameters
    + options (optional, string) - Options dictionary
      + Members
          + keyValues - when used, the request payload uses `keyValues` simplified entity representation. See "Simplified Entity Representation"
          section for details.

+ Response 201

    + Headers

            Location: /v2/entities/Bcn-Welt?type=Room


## Entity by ID [/v2/entities/{entityId}{?type,attrs,options}]

### Retrieve entity [GET /v2/entities/{entityId}{?type,attrs,options}]

The response is an object representing the entity identified by the ID. The object follows
the JSON entity representation format (described in "JSON Entity Representation" section).

This operation must return only one entity element, but it may happen that there are more
than one entity with the same ID (e.g. entities with same ID but different type). In those cases
an error mesage is returned, specifying in the description the URL that could be used to get
the list of conflicting entities, i.e. all the entities with such an ID.

Response:

* Successful operation uses 200 OK
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + entityId (required, string) - Entity id to be retrieved
    + type (optional, string) - Entity type, to avoid ambiguity in the case there are several
    entities with the same entity id.
    + attrs: temperature,humidity (optional, string) - Comma-separated list of attribute names which
    data will be included in the response. The attributes are retrieved in the order specified by this parameter.
    If this parameter is not included, all the attributes are retrieved in arbitrary order.
    + options (optional, string) - Options dictionary
      + Members
          + keyValues - when used, the response payload uses `keyValues` simplified entity representation. See 
          "Simplified Entity Representation" section for details.
          + values - when used, the response payload uses `values` simplified entity representation. See "Simplified Entity Representation"
          section for details.
          + unique - when used, the response payload uses `values` simplified entity representation. And, recurring values are left out.
          See "Simplified Entity Representation" section for details.

+ Response 200 (application/json)

        {
            "type": "Room",
            "id": "Bcn_Welt",
            "temperature": {
                "value": 21.7,
                "type": "none"
            },
            "humidity": {
                "value": 60,
                "type": "none"
            },
            "location": {
                "value": "41.3763726, 2.1864475",
                "type": "geo:point",
                "metadata": {
                    "crs": {
                        "value": "WGS84",
                        "type": "none"
                    }
                }
            }
        }

### Retrieve entity attributes [GET /v2/entities/{entityId}/attrs{?type,attrs,options}]

This request is similar to retreiving the whole entity, however this one omits `id` and `type` fields.

As the general way of getting a whole entity, this operation must return only one entity element,
but it may happen that there are more than one entity with the same ID (e.g. entities with same ID but different type). In those cases
an error mesage is returned, specifying in the description the URL that could be used to get
the list of conflicting entities, i.e. all the entities with such an ID.

Response:

* Successful operation uses 200 OK
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + entityId (required, string) - Entity id to be retrieved
    + type (optional, string) - Entity type, to avoid ambiguity in the case there are several
    entities with the same entity id.
    + attrs: temperature,humidity (optional, string) - Comma-separated list of attribute names which
    data will be included in the response. The attributes are retrieved in the order specified by this parameter.
    If this parameter is not included, all the attributes are retrieved in arbitrary order.
    + options (optional, string) - Options dictionary
      + Members
          + keyValues - when used, the response payload uses `keyValues` simplified entity representation. See
          "Simplified Entity Representation" section for details.
          + values - when used, the response payload uses `values` simplified entity representation. See "Simplified Entity Representation"
          section for details.
          + unique - when used, the response payload uses `values` simplified entity representation. And, recurring values are left out.
          See "Simplified Entity Representation" section for details.

+ Response 200 (application/json)

        {
            "temperature": {
                "value": 21.7,
                "type": "none"
            },
            "humidity": {
                "value": 60,
                "type": "none"
            },
            "location": {
                "value": "41.3763726, 2.1864475",
                "type": "geo:point",
                "metadata": {
                    "crs": {
                        "value": "WGS84",
                        "type": "none"
                    }
                }
            }
        }

### Update or append entity attributes [POST /v2/entities/{entityId}/attrs{?type,options}]

The request payload is an object representing the attributes to append or update. The object follows
the JSON entity representation format (described in "JSON Entity Representation" section), except that `id` and `type`
are not allowed.

The entity attributes are updated with the ones in the payload. In particular, depending on
whether `append` operation option is used or not.

* If `append` is not used: the entity attributes are updated (if they previously exist) or appended
  (in they don't previously exists) with the ones in the payload.
* If `append` is used (i.e. strict append semantics): all the attributes in the payload not previously
  existing in the entity are appended. In addition to that, in the case some of the attributes in the
  payload already exist in the entity, an error is returned.

Response:

* Successful operation uses 204 No Content
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + entityId (required, string) - Entity id to be updated
    + type (optional, string) - Entity type, to avoid ambiguity in the case there are several
    entities with the same entity id.
    + options (optional, string) - Operations options
        + Members
            + append - Force an append operation
            + keyValues - when used, the request payload uses `keyValues` simplified entity representation. See 
            "Simplified Entity Representation" section for details.

+ Request (application/json)

    + Body

            {
                "ambientNoise": {
                    "value": 31.5
                }
            }

+ Response 204

### Update existing entity attributes [PATCH /v2/entities/{entityId}/attrs{?type,options}]

The request payload is an object representing the attributes to update. The object follows
the JSON entity representation format (described in "JSON Entity Representation" section), except that `id` and `type`
are not allowed.

The entity attributes are updated with the ones in the payload. In addition to that, if one or more
attributes in the payload doesn't exist in the entity, an error if returned.

Response:

* Successful operation uses 204 No Content
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters 
    + entityId (required, string) - Entity id to be updated
    + type (optional, string) - Entity type, to avoid ambiguity in the case there are several
    entities with the same entity id.
    + options (optional, string) - Operations options
        + Members
            + keyValues - when used, the request payload uses `keyValues` simplified entity representation. See 
            "Simplified Entity Representation" section for details.

+ Request (application/json)

        {
            "temperature": {
                "value": 25.5
            },
            "seatsNumber": {
                "value": 6
            }
        }

+ Response 204

### Replace all entity attributes [PUT /v2/entities/{entityId}/attrs{?type,options}]

The request payload is an object representing the new entity attributes. The object follows
the JSON entity representation format (described in a "JSON Entity Representation" above), except that `id` and `type`
are not allowed.

The attributes previously existing in the entity are removed and replaced by the ones in the
request.

Response:

* Successful operation uses 204 No Content
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters 
    + entityId (required, string) - Entity id
    + type (optional, string) - Entity type, to avoid ambiguity in the case there are several
    entities with the same entity id.
    + options (optional, string) - Operations options
        + Members
            + keyValues - when used, the request payload uses `keyValues` simplified entity representation. See 
            "Simplified Entity Representation" section for details.

+ Request (application/json)

        {
            "temperature": {
                "value": 25.5
            },
            "seatsNumber": {
                "value": 6
            }
        }

+ Response 204

### Remove entity [DELETE /v2/entities/{entityId}{?type}]

Delete the entity.

Response:

* Successful operation uses 204 No Content
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters 
    + entityId (required, string) - Entity id to be deleted
    + type (optional, string) - Entity type, to avoid ambiguity in the case there are several
    entities with the same entity id.

+ Response 204


# Group Attributes

## Attribute by Entity ID [/v2/entities/{entityId}/attrs/{attrName}{?type}]

### Get attribute data [GET /v2/entities/{entityId}/attrs/{attrName}{?type}]

Returns a JSON object with the attribute data of the attribute. The object follows the JSON representation for attributes
(described in "JSON Entity Representation" section).

Response:

* Successful operation uses 20O OK.
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + entityId: Bcn_Welt (required, string) - Entity ID
    + type (optional, string) - Entity type, to avoid ambiguity in the case there are several
    entities with the same entity id.
    + attrName: temperature (required, string) - Attribute to be retrieved.

+ Response 200 (application/json)

        {
            "value": 21.7,
            "type": "none",
            "metadata": {}
        }

### Update attribute data [PUT /v2/entities/{entityId}/attrs/{attrName}{?type}]

The request payload is an object representing the new attributes data. Previous attribute data
is replaced by the one in the request. The object follows the JSON representation for attributes
(described in "JSON Entity Representation" section).

Response:

* Successful operation uses 204 No Content
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + entityId: Bcn_Welt (required, string) - Entity ID
    + type (optional, string) - Entity type, to avoid ambiguity in the case there are several
    entities with the same entity id.
    + attrName: temperature (required, string) - Attribute name

+ Request (application/json)

        {
            "value": 25.0,
            "metadata": {
                "unitCode": {
                   "value": "CEL"
                }
            }
        }

+ Response 200


### Remove a single attribute [DELETE /v2/entities/{entityId}/attrs/{attrName}{?type}]

Removes an entity attribute.

Response:

* Successful operation uses 204 No Content
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + entityId: Bcn_Welt (required, string) - Entity ID
    + type (optional, string) - Entity type, to avoid ambiguity in the case there are several
    entities with the same entity id.
    + attrName: temperature (required, string) - Attribute name

+ Response 204


# Group Attribute Value

## By Entity ID [/v2/entities/{entityId}/attrs/{attrName}/value?{type}]

### Get attribute value [GET /v2/entities/{entityId}/attrs/{attrName}/value{?type}]

It returns the `value` property with the value of the attribute.

* If response payload MIME type is `application/json`:
  * If attribute value is a JSON object or array, the payload in that JSON object or array
  * If attribute value is a string, number, null or boolean, a HTTP error "406 Not Acceptable: accepted MIME types:
    text/plain" is returned.
* If response payload MIME type is `text/plain`,
  * If attribute value is a JSON object or array, the payload in a stringification of that JSON object or array.
  * If attribute value is a string, number, null or boolean, the payload is a text representation of that value. In the case
    of a string, citation marks are used at the begining and end.

The payload MIME type in responses is based on client-server HTTP negotiation, based on client `Accept` header.

Response:

* Successful operation uses 20O OK.
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + entityId: Bcn_Welt (required, string) - Entity ID
    + type (optional, string) - Entity type, to avoid ambiguity in the case there are several
    entities with the same entity id.
    + attrName: temperature (required, string) - Attribute to be retrieved.

+ Response 200 (application/json)

        {
            "address": "Ronda de la Comunicacion s/n",
            "zipCode": 28050,
            "city": "Madrid",
            "country": "Spain"
        }

### Update attribute value [PUT /v2/entities/{entityId}/attrs/{attrName}/value{?type}]

The request payload is the new attribute value.

* If the request payload MIME type is `application/json`, then the value of the attribute is set to the JSON object or array
  coded in the payload (if the payload is not a valid JSON document, then an error is returned).
* If the request payload MIME type is `text/plain`, then the following algorithm is applied to the payload:
  * If the payload starts and ends with citation-marks (`"`), the value is taken as a string (the citation marks themselves are not
    considered part of the string)
  * If `true` or `false`, the value is taken as a boolean.
  * If `null`, the value is taken as null.
  * If these first three tests 'fail', the text is interpreted as a number.
  * If not a number, then an error is returned and the attribute's value is unchanged.

The payload MIME type in request is specified in the `Content-Type` HTTP header.

Response:

* Successful operation uses 204 No Content
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + entityId: Bcn_Welt (required, string) - Entity ID
    + type (optional, string) - Entity type, to avoid ambiguity in the case there are several
    entities with the same entity id.
    + attrName: temperature (required, string) - Attribute name

+ Request (application/json)

        {
            "address": "Ronda de la Comunicacion s/n",
            "zipCode": 28050,
            "city": "Madrid",
            "country": "Spain"
        }

+ Response 200

# Group Types

## Entity types [/v2/types{?limit,offset,options}]

### Retrieve entity types [GET /v2/types/{?limit,offset,options}]

If `values` option is not in use, the operation returns a JSON array with the entity types. Each element
is a JSON object with information about the type:

* `type` : the entity type name.
* `attrs` : the set of attribute names along with all the entities of such type, represented in
  a JSON object whose keys are the attribute names and whose values contain information of such
  attributes (in particular a list of the types used by attributes with that name along all the
  entities).
* `count` : the number of entities belonging to that type.

If `values` option is used, the operation returns a JSON array with the list of entity type names as strings.

Results are ordered by entity `type` in alphabetical order.

Response code:

* Successful operation uses 200 OK
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + limit: 10 (optional, number) - Limit the number of types to be retrieved
    + offset: 20 (optional, number) - Skip a number of records
    + options (optional, string) - Options dictionary
      + Members
          + count - when used, the total types number is returned as a HTTP in the response named `Fiware-Total-Count`
          + values - when used, the response payload is a JSON array with a list of entity types

+ Response 200 (application/json)

        [
          {
            "type": "Car",
            "attrs": {
              "speed": {
                "types": [ "none" ]
              },
              "fuel": {
                "types": [ "gasoline", "diesel" ]
              },
              "temperature": {
                "types": [ "urn:phenomenum:temperature" ]
              }
            },
            "count": 12
          },
          {
            "type": "Room",
            "attrs": {
              "pressure": {
                "types": [ "none" ]
              },
              "humidity": {
                "types": [ "percentage" ]
              },
              "temperature": {
                "types": [ "urn:phenomenum:temperature" ]
              }
            },
            "count": 7
          }
        ]

## Entity type [/v2/types/{entityType}]

### Retrieve entity type [GET /v2/types/{entityType}]

The operation returns a JSON object with information about the type:

* `attrs` : the set of attribute names along with all the entities of such type, represented in
  a JSON object whose keys are the attribute names and whose values contain information of such
  attributes (in particular a list of the types used by attributes with that name along all the
  entities).
* `count` : the number of entities belonging to that type.

Response code:

* Successful operation uses 200 OK
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + entityType: Room (required, string) - Entity Type

+ Response 200 (application/json)

          {
            "attrs": {
              "pressure": {
                "types": [ "none" ]
              },
              "humidity": {
                "types": [ "percentage" ]
              },
              "temperature": {
                "types": [ "urn:phenomenum:temperature" ]
              }
            },
            "count": 7
          }

# Group Subscriptions

A subscription is represented by a JSON object with the following fields:

+ `id`: Subscription unique identifier. Automatically created at creation time.
+ `description` (optional): A free text used by the client to describe the subscription.
+ `subject`: It is an object that describes the subject of the subscription.
+ `notification`: It is an object that describes the notification received by the subscriber.
+ `expires`: Subscription expiration date in ISO8601 format. Permanent subscriptions must omit
   this field.
+ `status`: Either `active` (for active subscriptions) or `inactive` (for inactive subscriptions).
  If this field is not provided at subscription creation time, new subscriptions are created with
  the `active` status, which can be changed by clients afterwards. For expired subscriptions this
  attribute is set to `expired` value (no matter if the client updates it to `active`/`inactive`).
+ `throttling`: Minimal period of time in seconds which must elapse between two consecutive notifications. It
  is optional.

A `subject` contains the following subfields:

+ `entities`: A list of objects, each one composed of the following subfields (`id`/`idPattern` or `type` must be present):
    + `id` or `idPattern`: Id or pattern of the affected entities. Both cannot be used at the same time, but at least one of them must be set.
    + `type`: Type of the affected entities (optional).
+ `condition`: Condition that will trigger the notification. It can have two optional properties:
    + `attrs`: array of attribute names
    + `expression`: an expression composed of `q`, `georel`, `geometry` and `coords` (see "List entities" operation above
   about this field).

A `notification` object contains the following subfields:

+ `attrs` or `exceptAttrs` (both cannot be used at the same time):
  + `attrs`: List of attributes to be included in the notification message. It also defines the order in which attributes
    appear in notifications when `attrsFormat` `value` is used (see "Notification Messages" section). Empty list means that
    all attributes are included in the notification.
  + `exceptAttrs`: List of attributes to be excluded from the notification message, i.e. notification message includes
     all entity attributes except the ones listed in this field.
  + If neither `attrs` nor `exceptAttrs` is specified, all attributes are included in the notification.
+ `http` or `httpCustom` (one of them has to be used, but not both at the same time): It is used to convey parameters
  for notifications delivered through the HTTP protocol.
+ `attrsFormat` (optional): specifies how the entities will be represented in notifications. Accepted values are
  `normalized` (the one used if the field is omitted), `keyValues` or `values`. If `attrsFormat` takes any value different
  than those an error will be raised. See detail in "Notification Messages" section.
+ `timesSent` (not editable, only in GET operations): Number of notifications sent due to this subscription.
+ `lastNotification`: Last notification date in ISO8601 format.

An `http` object contains the following subfields:

+ `url` : URL referencing the service which is invoked when a notification is generated. A NGSIv2
  compliant server must support `http` URL schema, other schemas could also be supported.

An `httpCustom` object contains the following subfields.

+ `url`: same as in `http` above.
+ `headers` (optional): a key-map of HTTP headers that are included in the notification messages.
+ `qs` (optional): a key-map of URL query parameters that are included in the notification message.
+ `method` (optional): the method to use for sending the notification (default is POST). Only valid HTTP methods are allowed.
   On specifying an invalid HTTP method, a 400 Bad Request error is returned.
+ `payload` (optional): the payload to be used in the notification. If omitted, the default payload (see
  "Notification Messages" sections) is used.

If `httpCustom` is used, then the considerations described in "Custom Notifications" section apply.

Notification rules are as follow:

* If `attrs` and `expression` are used, a notification is sent whenever one of the attributes in the `attrs` list changes and
  at the same time `expression` matches.
* If `attrs` is used and `expression` is not used, a notification is sent whenever one of the attributes in the `attrs` list changes-
* If `attrs` is not used and `expression` is used, a notification is sent whenever any of the attributes of the entity changes and
  at the same time `expression` matches.
* If neither `attrs` or `expression` are used, a notification is sent whenever any of the attributes of the entity changes.

## Subscription List [/v2/subscriptions]

### Retrieve subscriptions [GET /v2/subscriptions]

Returns a list of all the subscriptions present in the system

Response:

* Successful operation uses 200 OK
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + limit: 10 (optional, number) - Limit the number of types to be retrieved
    + offset: 20 (optional, number) - Skip a number of records
    + options (optional, string) - Options dictionary
      + Members
          + count - when used, the total subscriptions number is returned as a HTTP in the response named `Fiware-Total-Count`

+ Response 200

        [
            {
                "id": "abcdefg",
                "description": "One subscription to rule them all",
                "subject": {                    
                    "entities": [
                        {
                            "id": "Bcn_Welt",
                            "type": "Room"
                        }
                    ],
                    "condition": {
                       "attrs": [ "temperature " ],
                       "expression": {
                          "q": "temperature>40"
                       }
                    }
                },
                "notification": {
                    "httpCustom": {
                      "url": "http://localhost:1234",
                      "headers": {
                        "X-MyHeader": "foo"
                      },
                      "qs": {
                        "authToken": "bar"
                      }
                    },
                    "attrsFormat": "keyValues",
                    "attrs": ["temperature", "humidity"],
                    "timesSent": 12,
                    "lastNotification": "2015-10-05T16:00:00.00Z"
                },
                "expires": "2016-04-05T14:00:00.00Z",
                "status": "active",
                "throttling": 5
            }
        ]


### Create a new subscription [POST /v2/subscriptions]

Creates a new subscription.
The subscription is represented by a JSON object as described at the beginning of this section.

Response:

* Successful operation uses 201 Created
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Request (application/json)

        {
            "description": "One subscription to rule them all",
            "subject": {
                "entities": [
                    {
                        "idPattern": ".*",
                        "type": "Room"
                    }
                ],
                "condition": {
                    "attrs": [ "temperature" ],
                    "expression": {
                       "q": "temperature>40"
                    }
                 }
            },
            "notification": {
                "http": {
                  "url": "http://localhost:1234"
                },
                "attrs": ["temperature", "humidity"]
            },            
            "expires": "2016-04-05T14:00:00.00Z",
            "throttling": 5
        }

+ Response 201

    + Headers

            Location: /v2/subscriptions/abcde98765


## Subscription By ID [/v2/subscriptions/{subscriptionId}]

### Retrieve subscription [GET /v2/subscriptions/{subscriptionId}]

The response is the subscription represented by a JSON object as described at the beginning of this section.

Response:

* Successful operation uses 200 OK
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + subscriptionId: abcdef (required, string) - subscription Id.

+ Response 200 (application/json)

        {
            "id": "abcdef",
            "description": "One subscription to rule them all",
            "subject": {
                "entities": [
                    {
                        "idPattern": ".*",
                        "type": "Room"
                    }
                ],
                "condition": {
                    "attrs": [ "temperature " ],
                    "expression": {
                       "q": "temperature>40"
                    }
                 }
            },
            "notification": {
                "http": {
                  "url": "http://localhost:1234"
                },
                "attrs": ["temperature", "humidity"],
                "timesSent": 12,
                "lastNotification": "2015-10-05T16:00:00.00Z"
            },
            "expires": "2016-04-05T14:00:00.00Z",
            "status": "active",
            "throttling": 5,
        }


### Update subscription [PATCH /v2/subscriptions/{subscriptionId}]

Only the fields included in the request are updated in the subscription.

Response:

* Successful operation uses 204 No Content
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + subscriptionId: abcdef (required, string) - subscription Id.

+ Request (application/json)

        {
            "expires": "2016-04-05T14:00:00.00Z"
        }

+ Response 204

### Delete subscription [DELETE /v2/subscriptions/{subscriptionId}]

Cancels subscription.

Response:

* Successful operation uses 204 No Content
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + subscriptionId: abcdef (required, string) - subscription Id.

+ Response 204

# Group Registrations

Context Registration allows to associate external services to context data. One of the main
use cases of this functionality is the association of Context Providers.

A context registration is represented by a JSON object with the following fields:

+ `id`       : Unique identifier assigned to the registration. Automatically generated at creation time.
+ `subject`  : It is an object that describes the subject of the registration.
+ `callback` : URL which denotes the end point of the registered service. It is optional, as it can be
undefined under certain conditions, for instance, transient unavailability of the provider.
+ `metadata` : An optional JSON object which allows to associate extra metadata properties to the registration.
It must follow the same representation conventions as context attribute metadata (See JSON Attribute Representation). 
+ `duration` : Duration of the registration in ISO8601 format. Default duration is infinite.

A `subject` contains the following subfields:

+ `entities`: A list of objects, each one composed of the following subfields (`id`/`idPattern` or type must be present):
    + `id` or `idPattern`: Id or pattern of the affected entities. Both cannot be used at the same time, but at least one of them must be set.
    + `type`: Type of the affected entities (optional).
+ `attributes`: List of attributes to be provided (if not specified it would mean all).

## Registration list [/v2/registrations]

### Retrieve registrations [GET /v2/registrations]

Lists all the registrations present in the system.

Response:

* Successful operation uses 200 OK
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Response 200

        [
            {
                "id": "abcdefg",
                "subject": {
                    "entities": [
                        {
                            "id": "Bcn_Welt",
                            "type": "Room"
                        }
                    ],
                    "attributes": [
                        "temperature"
                    ]
                },
                "callback": "http://weather.example.com/ngsi",
                "metadata": {
                    "providingService": {
                       "value": "weather.example.com",
                       "type": "none"
                     },
                    "providingAuthority": {
                       "value": "AEMET - Spain",
                       "type": "none"
                     }
                },
                "duration": "PT1M"
            }
        ]

### Create a new context provider registration [POST /v2/registrations]

Creates a new registration. This is typically used for associating context providers
to certain data.
The registration is represented by a JSON object as described at the beginning of this section.

Response:

* Successful operation uses 201 Created
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Request (application/json)

        {
            "subject": {
                "entities": [
                    {
                        "id": "room2",
                        "type": "Room"
                    }
                ],
                "attributes": [
                      "humidity"
                ]
            },
            "callback":  "http://localhost:1234",
            "metadata" : {
                "provider": {
                   "value": "example.com"
                }
            },
            "duration": "PT1M"
        }

+ Response 201

    + Headers

            Location: /v2/registrations/abcde98765

## Registration By ID [/v2/registrations/{registrationId}]

### Retrieve context provider registration [GET /v2/registrations/{registrationId}]

The response is the registration represented by a JSON object as described at the beginning of this section.

Response:

* Successful operation uses 200 OK
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + registrationId: abcdef (required, string) - registration Id.

+ Response 200 (application/json)

        {
            "id": "abcde",
            "subject": {
                "entities": [
                    {
                        "id": "room2",
                        "type": "Room"
                    }
                ],
                "attributes": [
                      "humidity"
                ]
            },
            "callback":  "http://localhost:1234",
            "duration": "PT1M"
        }

### Update context provider registration [PATCH /v2/registrations/{registrationId}]

Only the fields included in the request are updated in the registration.

Response:

* Successful operation uses 204 No Content
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + registrationId: abcdef (required, string) - registration Id.

+ Request (application/json)

        {
            "duration": "PT1M"
        }

+ Response 204

### Delete context provider registration [DELETE /v2/registrations/{registrationId}]

Cancels registration.

Response:

* Successful operation uses 204 No Content
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + registrationId: abcdef (required, string) - registration Id.

+ Response 204

# Group Batch Operations

### Update [POST /v2/op/update]

This operation allows to create, update and/or delete several entities in a single batch operation.
The payload is an object with two properties:

+ `actionType`, to specify the kind of update action to do: either APPEND, APPEND_STRICT, UPDATE, DELETE.
+ `entities`, an array of entities, each one specified using the JSON entity representation format (described
  in "JSON Entity Representation" section).

Response:

* Successful operation uses 204 No Content.
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Request (application/json)

        {
            "actionType": "APPEND",
            "entities": [
                {
                    "type": "Room",
                    "id": "Bcn-Welt",
                    "temperature": {
                      "value": 21.7
                     },
                    "humidity": {
                      "value": 60
                    }
                },
                {
                    "type": "Room",
                    "id": "Mad_Aud",
                    "temperature": {
                      "value": 22.9
                    },
                    "humidity": {
                      "value": 85
                    }
                }
            ]
        }

+ Parameters
    + options (optional, string) - Options dictionary
      + Members
          + keyValues - when used, the request payload uses `keyValues` simplified entity representation. See "Simplified Entity Representation"
          section for details.

+ Response 204


### Query [POST /v2/op/query{?limit,offset,options}]

The response payload is an Array which contains one object per matching entity. Each entity follows
the JSON entity representation format (described in "JSON Entity Representation" section).

The payload may contain the following elements (all of them optional):

+ `entities`: a list of entites to search for. Each entity is represented by a JSON object with the following
  elements:
    + `id` or `idPattern`: Id or pattern of the affected entities. Both cannot be used at the same time, but at least one of them must be set.
    + `type`: specifies the type of the entities to search for. If omitted, it means "any entity type".
+ `attributes`: a list of attributes names to search for. If omitted, it means "any attribute".
+ `scopes`: a list of scopes to restrict the results of the query. Each scope is represented by a JSON
   object with a `type` (a JSON string) and `value` (whose type depends on the `type` property). The
   different available scopes are described elsewhere.

Response code:

* Successful operation uses 200 OK
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + limit: 10 (optional, number) - Limit the number of entities to be retrieved
    + offset: 20 (optional, number) - Skip a number of records
    + orderBy: temperature,!speed (optional, string) - Criteria for ordering results. See "Ordering Results" section for details.
    + options (optional, string) - Options dictionary
      + Members
          + count - the total number of entities is returned in the response as an
          HTTP header named `Fiware-Total-Count`.
          + keyValues - when used, the response payload uses `keyValues` simplified entity representation. See "Simplified Entity Representation"
          section for details.
          + values - when used, the response payload uses `values` simplified entity representation. See "Simplified Entity Representation"
          section for details.
          + unique - when used, the response payload uses `values` simplified entity representation. And, recurring values are left out.
          See "Simplified Entity Representation" section for details.


+ Request (application/json)

        {
            "entities": [
                {
                    "idPattern": ".*",
                    "type": "myFooType"
                },
                {
                    "id": "myBar",
                    "type": "myBarType"
                }
            ],
            "attributes": [
                "temperature",
                "humidity"
            ],
            "scopes": [
                {
                    "type": "FIWARE::...",
                    "value": "..."
                }
            ]
        }

+ Response 200 (application/json)

        [
         {
            "type": "Room",
            "id": "DC_S1-D41",
            "temperature": {
              "value": 35.6,
              "type": "none"
            }
         },
         {
            "type": "Room",
            "id": "Boe-Idearium",
            "temperature": {
              "value": 22.5,
              "type": "none"
            }
         },
         {
            "type": "Car",
            "id": "P-9873-K",
            "speed": {
                "value": 100,
                "type": "number",
                "accuracy": 2,
                "timestamp": {
                    "value": "2015-06-04T07:20:27.378Z",
                    "type": "date"
                }
            }
         }
        ]


### Register [POST /v2/op/register]

This operation allows to create, update and/or delete several registrations in a single batch operation.
The payload is an object with two properties:

+ `actionType`, to specify the kind of register action to do: either CREATE, UPDATE, DELETE.
+ `registrations`, an array of registration, each one specified using the JSON registration representation
  format (described in a section above). In the case of CREATE operation, the registration `id` must not be
  included.

Response:

* Successful operation uses 200 OK. In addition, in the case of successful CREATE, a list of IDs is returned,
  each one corresponding to the ID of the element in the request payload and in the same order.
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Request (application/json)

        {
          "actionType": "CREATE",
          "registrations": [
             {
               "subject": {
                  "entities": [
                     {
                        "type": "Room"
                     }
                  ],
                  "attributes": [
                     "humidity"
                 ]
               },
               "callback": "http://localhost:1234",
               "duration": "PT1M"
             },
             {
               "subject": {
                 "entities": [
                    {
                       "type": "Car"
                    }
                 ],
                 "attributes": [
                   "speed"
                 ]
               },
               "callback": "http://localhost:5678",
               "duration": "PT1M"
             }
          ]
        }

+ Response 200

        [
          "abcd",
          "efgh"
        ]


### Discover [POST /v2/op/discover/{?limit,offset,options}]

The response payload is an Array which contains one object per matching registration. Each registration follows
the JSON registration representation format (described in a section above).

The payload may contain the following elements (all of them optional):

+ `entities`: a list of entites to search for. Each entity is represented by a JSON object with the following
  elements:
    + `id` or `idPattern`: Id or pattern of the affected entities. Both cannot be used at the same time, but at least one of them must be set.
    + `type`: specifies the type of the entities to search for. If omitted, it means "any entity type".
+ `attributes`: a list of attributes names to search for. If omitted, it means "any attribute".
+ `scopes`: a list of scopes to restrict the results of the query. Each scope is represented by a JSON
   object with a `type` (a JSON string) and `value` (whose type depends on the `type` property). The
   different available scopes are described elsewhere.

Response code:

* Successful operation uses 200 OK
* Errors use a non-2xx and (optionally) an error payload. See subsection on "Error Responses" for more details.

+ Parameters
    + limit: 10 (optional, number) - Limit the number of registrations to be retrieved
    + offset: 22 (optional, number) - Skip a number of registrations
    + options (optional, string) - Options dictionary
        + Members
          + count - when used, the total number of registrations is returned in the response as a HTTP header named `Fiware-Total-Count`


+ Request (application/json)

        {
          "entities": [
            {
              "idPattern": ".*",
              "type": "myFooType"
            },
            {
              "id": "myBar",
              "type": "myBarType"
            }
          ],
          "attributes": [
            "temperature",
            "humidity"
          ],
          "scopes": [
            {
              "type": "FIWARE::Filter::Foo",
              "value": "Bar"
            }
          ]
        }

+ Response 200 (application/json)

        [
          {
            "id": "abcde",
            "subject": {
              "entities": [
                {
                  "id": "Foo",
                  "type": "myFooType"
                }
              ],
              "attributes": [
                "humidity"
              ]
            },
            "callback": "http://localhost:1234",
            "duration": "PT1M"
          },
          {
            "id": "efgh",
            "subject": {
              "entities": [
                {
                  "id": "myBar",
                  "type": "myBarType"
                }
              ],
              "attributes": [
                "speed"
              ]
            },
            "callback": "http://localhost:5678",
            "duration": "PT1M"
          }
        ]

# Group OMA-NGSI Operations

(The need/usefulness of these operations is currently under discussion)

For the sake of completeness here is an enumeration of the OMA-NGSI (9 & 10) operations. These
operations will be supported under the 'v2' resource as well.

### subscribeContext [POST /v2/subscribeContext]

(Not needed, a it is covered by the RESTful POST /v2/subscriptions operation)

### updateContextSubscription [POST /v2/updateContextSubscription]

(Not needed, a it is covered by the RESTful PATCH /v2/subscriptions operation)

### unsubscribeContext [POST /v2/unsubscribeContext]

(Not needed, a it is covered by the RESTful DELETE /v2/subscriptions operation)

### notifyContext [POST /v2/notifyContext]

(The payload of the v2 notifyContext should be described)

### subscribeContextAvailability [POST /v2/subscribeContextAvailability]

(Not needed as POJ RPC, but we need to define a RESTful operation for this, analogous to the NGSI10 one)

### updateContextAvailabilitySubscription [POST /v2/updateContextAvailabilitySubscription]

(Not needed as POJ RPC, but we need to define a RESTful operation for this, analogous to the NGSI10 one)

### unsubscribeContextAvailability [POST /v2/unsubscribeContextAvailability]

(Not needed as POJ RPC, but we need to define a RESTful operation for this, analogous to the NGSI10 one)

### notifyContextAvailability [POST /v2/notifyContextAvailability]

(The payload of the v2 notifyContextAvailability should be described)
