# Valgrind action is a heavy process that can take arround 50 minutes to finish. Thus, we don't want
# this to be executed in every pull request but only intentionally on specific branches. In particular,
# the action is configured so it will run in branches starting with 'checkvalgrind'

name: Valgrind Tests

on:
  push:
    branches:
      - checkvalgrind**

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
   TEST_IMAGE_NAME: telefonicaiot/fiware-orion:ci

jobs:
  valgrind:
    runs-on: ubuntu-22.04
    continue-on-error: true

    strategy:
      matrix:
        batch:
          - { name: "batch 1 - cache", FT_FROM_IX: 0,   FT_TO_IX: 300,  CB_NO_CACHE: ""  }
          - { name: "batch 2 - cache", FT_FROM_IX: 301, FT_TO_IX: 600,  CB_NO_CACHE: ""  }
          - { name: "batch 3 - cache", FT_FROM_IX: 601, FT_TO_IX: 900,  CB_NO_CACHE: ""  }
          - { name: "batch 4 - cache", FT_FROM_IX: 901, FT_TO_IX: 1200, CB_NO_CACHE: ""  }
          - { name: "batch 5 - cache", FT_FROM_IX: 1201,FT_TO_IX: "",   CB_NO_CACHE: ""  }

    name: valgrind - ${{ matrix.batch.name }}

    steps:
      - uses: actions/checkout@v2

      - name: Run valgrind test
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          FT_FROM_IX: ${{ matrix.batch.FT_FROM_IX }}
          FT_TO_IX:   ${{ matrix.batch.FT_TO_IX }}
          CB_NO_CACHE: ${{ matrix.batch.CB_NO_CACHE }}
          TEST_IMAGE_NAME: ${{ env.TEST_IMAGE_NAME }}
        run: |
          docker compose \
            --project-name valgrind-${{ github.run_id }}-${{ strategy.job-index }} \
            -f ./ci/deb/docker-compose-ci.yml -f ./ci/deb/docker-compose-ci.valgrind.yml \
            --project-directory . \
            up  --build --abort-on-container-exit --exit-code-from tests \
            --attach tests \
            --no-log-prefix
